# Generated by Django 5.1.6 on 2025-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipe_name', models.CharField(max_length=50)),
                ('receipe_description', models.TextField()),
                ('Receipe_image', models.ImageField(upload_to='receipe_images')),
            ],
        ),
    ]
