# Generated by Django 5.1.6 on 2025-03-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0003_department_studentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
